-- Run once in Supabase SQL Editor after schema.sql.
-- This imports the existing website itineraries and gallery into content_items.
insert into public.content_items (type, title, slug, excerpt, body, image_url, published, metadata)
values
('itinerary', 'Bale Mountains Birding', 'bale-mountains-birding', '7 days of endemic birding, mountain views, and wild landscapes.', 'Day 1: Arrival in Addis and transfer to the highlands.\nDay 2: Birding in the Bale Mountains.\nDay 3: Sanetti Plateau wildlife viewing.\nDay 4: Forest birding and local communities.\nDay 5: Mountain trails and endemic species.\nDay 6: Final birding excursion.\nDay 7: Return to Addis.', 'https://upload.wikimedia.org/wikipedia/commons/8/81/Bale_mountains.jpg', true, '{"source":"itinerary-bale.html","days":7}'),
('itinerary', 'Omo Valley Cultural', 'omo-valley-cultural', '10 days of cultural discovery and meaningful local encounters.', 'Day 1: Fly or drive to the Omo Valley.\nDay 2: Visit the Hamer people.\nDay 3: Explore local markets and villages.\nDay 4: Travel through the lower Omo region.\nDay 5: Cultural exchange with local communities.\nDay 6: Visit Konso landscapes.\nDay 7: Traditional ceremonies and crafts.\nDay 8: Scenic travel and photography.\nDay 9: Community visit and farewell.\nDay 10: Return journey.', 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Hamar_woman.jpg', true, '{"source":"itinerary-omo.html","days":10}'),
('itinerary', 'Danakil and Lalibela', 'danakil-lalibela', '14 days of extreme landscapes and sacred heritage across northern Ethiopia.', 'Day 1: Arrive in Addis and rest.\nDay 2: Travel to Bahir Dar and Lake Tana.\nDay 3: Continue toward Lalibela.\nDay 4: Explore the rock-hewn churches.\nDay 5: Travel toward the Danakil Depression.\nDay 6: Desert expedition and salt flats.\nDay 7: Volcanic landscapes and mineral formations.\nDay 8: Remote desert communities.\nDay 9: Return from the expedition.\nDay 10: Historic northern route.\nDay 11: Heritage and local culture.\nDay 12: Scenic mountain travel.\nDay 13: Return to Addis.\nDay 14: Departure.', 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&q=80', true, '{"source":"itinerary-danakil.html","days":14}'),
('image', 'Bale Mountains', 'gallery-bale-mountains', 'Sanetti Plateau in the Bale Mountains, Ethiopia.', 'Birding destination gallery image.', 'https://upload.wikimedia.org/wikipedia/commons/8/81/Bale_mountains.jpg', true, '{"category":"Birding","alt":"Birding in Bale Mountains"}'),
('image', 'Omo Valley', 'gallery-omo-valley', 'Hamar culture in Ethiopia’s Omo Valley.', 'Culture destination gallery image.', 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Hamar_woman.jpg', true, '{"category":"Culture","alt":"Omo Valley culture"}'),
('image', 'Lalibela', 'gallery-lalibela', 'Rock-hewn church heritage in Lalibela.', 'Heritage destination gallery image.', 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80', true, '{"category":"Heritage","alt":"Lalibela heritage"}'),
('image', 'Danakil', 'gallery-danakil', 'The dramatic Danakil landscape.', 'Adventure destination gallery image.', 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80', true, '{"category":"Adventure","alt":"Danakil adventure"}'),
('image', 'Simien Mountains', 'gallery-simien', 'Mountain scenery and hiking in Ethiopia.', 'Hiking destination gallery image.', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&q=80', true, '{"category":"Birding","alt":"Simien Mountains hiking"}'),
('image', 'Addis Ababa', 'gallery-addis', 'City life in Ethiopia’s capital.', 'City destination gallery image.', 'https://images.unsplash.com/photo-1523908511403-7fc7b25592f4?w=800&q=80', true, '{"category":"Culture","alt":"Addis Ababa city life"}')
on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, body = excluded.body, image_url = excluded.image_url, published = excluded.published, metadata = excluded.metadata, updated_at = now();
