const API_BASE = (window.TRAVERSE_API_URL || '').replace(/\/$/, ''); const apiUrl = path => `${API_BASE}${path}`; const $ = id => document.getElementById(id); let token = localStorage.getItem('traverse_admin_token'); let editingId = null;
function status(id, message, error = false) { $(id).textContent = message; $(id).style.color = error ? '#a33' : '#276749;'; }
async function request(url, options = {}) { const response = await fetch(apiUrl(url), { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed'); return data; }
function showDashboard() { $('loginPanel').classList.add('hidden'); $('dashboard').classList.remove('hidden'); loadItems(); }
$('loginForm').addEventListener('submit', async e => { e.preventDefault(); try { const data = await request('/api/admin/login', { method: 'POST', body: JSON.stringify({ username: $('adminUsername').value, password: $('adminPassword').value }) }); token = data.token; localStorage.setItem('traverse_admin_token', token); showDashboard(); } catch (error) { status('loginStatus', error.message, true); } });
async function loadItems() { try { const data = await request('/api/admin/content'); $('items').innerHTML = data.items.length ? data.items.map(item => `<article class="item"><div><strong>${escapeHtml(item.title)}</strong><div class="muted">${item.type} · ${item.published ? 'Published' : 'Draft'}</div></div><div class="actions"><button class="btn edit" data-id="${item.id}">Edit</button><button class="btn delete" data-id="${item.id}">Delete</button></div></article>`).join('') : '<p class="muted">No content yet.</p>'; document.querySelectorAll('.edit').forEach(button => button.onclick = () => editItem(data.items.find(x => x.id === button.dataset.id))); document.querySelectorAll('.delete').forEach(button => button.onclick = () => deleteItem(button.dataset.id)); } catch (error) { status('contentStatus', error.message, true); } }
function editItem(item) { editingId = item.id; ['type','title','slug','image_url','excerpt','body'].forEach(key => $(key).value = item[key] || ''); $('published').checked = !!item.published; window.scrollTo({ top: 0, behavior: 'smooth' }); }
async function deleteItem(id) { if (!confirm('Delete this content?')) return; try { await request(`/api/admin/content/${id}`, { method: 'DELETE' }); loadItems(); } catch (error) { status('contentStatus', error.message, true); } }
$('contentForm').addEventListener('submit', async e => { e.preventDefault(); const item = { type: $('type').value, title: $('title').value.trim(), slug: $('slug').value.trim() || undefined, image_url: $('image_url').value.trim() || undefined, excerpt: $('excerpt').value.trim(), body: $('body').value.trim(), published: $('published').checked }; try { await request(editingId ? `/api/admin/content/${editingId}` : '/api/admin/content', { method: editingId ? 'PUT' : 'POST', body: JSON.stringify(item) }); status('contentStatus', 'Content saved successfully.'); $('clear').click(); loadItems(); } catch (error) { status('contentStatus', error.message, true); } });
$('clear').onclick = () => { editingId = null; $('contentForm').reset(); }; $('logout').onclick = () => { localStorage.removeItem('traverse_admin_token'); token = null; location.reload(); }; function escapeHtml(value) { return String(value).replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[char])); } if (token) showDashboard();
