const crypto = require('crypto');

const SUPABASE_URL = (process.env.SUPABASE_URL || 'https://zuxmocwkyntfekqpujee.supabase.co').replace(/\/$/, '');
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SECRET_KEY;
const sessions = new Set();
const gallery = [
  { title: 'Bale Mountains', category: 'Birding', image: 'https://upload.wikimedia.org/wikipedia/commons/8/81/Bale_mountains.jpg', alt: 'Sanetti Plateau in the Bale Mountains, Ethiopia' },
  { title: 'Omo Valley', category: 'Culture', image: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Hamar_woman.jpg', alt: 'Hamar woman in Ethiopia’s Omo Valley' },
  { title: 'Lalibela', category: 'Heritage', image: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Bete_Giyorgis%2C_Lalibela%2C_Ethiopia.jpg', alt: 'Bete Giyorgis rock-hewn church in Lalibela' },
  { title: 'Danakil', category: 'Adventure', image: 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Danakil_Depression_Ethiopia.jpg', alt: 'Danakil Depression in Ethiopia' },
  { title: 'Simien Mountains', category: 'Hiking', image: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Simien_Mountains%2C_Ethiopia.jpg', alt: 'Simien Mountains in Ethiopia' },
  { title: 'Addis Ababa', category: 'City', image: 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Addis_Ababa%2C_Ethiopia.jpg', alt: 'Addis Ababa, Ethiopia' }
];
function sendJson(res, statusCode, payload) { res.writeHead(statusCode, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }); res.end(JSON.stringify(payload)); }
function readBody(req) { return new Promise((resolve, reject) => { let body = ''; req.on('data', chunk => { body += chunk; if (Buffer.byteLength(body) > 1e6) reject(new Error('Payload too large')); }); req.on('end', () => { if (!body) return resolve({}); try { return resolve(JSON.parse(body)); } catch (_) {} try { const parsed = {}; new URLSearchParams(body).forEach((v, k) => { parsed[k] = v; }); resolve(parsed); } catch (_) { reject(new Error('Invalid request body')); } }); req.on('error', reject); }); }
function healthHandler(req, res) { sendJson(res, 200, { ok: true, message: 'Traverse Ethiopia API is healthy', service: 'traverse-ethiopia', timestamp: new Date().toISOString() }); }
function galleryHandler(req, res) { sendJson(res, 200, { ok: true, items: gallery }); }
async function supabase(path, options = {}) { if (!SUPABASE_KEY) throw new Error('Database is not configured on the server.'); const response = await fetch(`${SUPABASE_URL}/rest/v1/${path}`, { ...options, headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}`, 'Content-Type': 'application/json', ...(options.headers || {}) } }); const text = await response.text(); let data; try { data = text ? JSON.parse(text) : null; } catch (_) { data = text; } if (!response.ok) throw new Error(data?.message || data?.hint || 'Database request failed'); return data; }
async function contentHandler(req, res, params) { try { const type = params.get('type'); const query = type ? `content_items?select=*&type=eq.${encodeURIComponent(type)}&published=eq.true&order=created_at.desc` : 'content_items?select=*&published=eq.true&order=created_at.desc'; return sendJson(res, 200, { ok: true, items: await supabase(query) }); } catch (error) { return sendJson(res, 500, { ok: false, error: error.message }); } }
function tokenFrom(req) { const value = req.headers.authorization || ''; return value.startsWith('Bearer ') ? value.slice(7) : ''; }
function requireAdmin(req, res) { if (!sessions.has(tokenFrom(req))) { sendJson(res, 401, { ok: false, error: 'Admin authentication required.' }); return false; } return true; }
async function adminLoginHandler(req, res) { try { const body = await readBody(req); if (!process.env.ADMIN_EMAIL || !process.env.ADMIN_PASSWORD) return sendJson(res, 503, { ok: false, error: 'Admin credentials are not configured.' }); if (body.email !== process.env.ADMIN_EMAIL || body.password !== process.env.ADMIN_PASSWORD) return sendJson(res, 401, { ok: false, error: 'Invalid admin credentials.' }); const token = crypto.randomBytes(32).toString('hex'); sessions.add(token); sendJson(res, 200, { ok: true, token }); } catch (error) { sendJson(res, 400, { ok: false, error: error.message }); } }
async function adminContentHandler(req, res, params, id) { if (!requireAdmin(req, res)) return; try { if (req.method === 'GET') return sendJson(res, 200, { ok: true, items: await supabase('content_items?select=*&order=created_at.desc') }); if (req.method === 'DELETE') { await supabase(`content_items?id=eq.${encodeURIComponent(id)}`, { method: 'DELETE' }); return sendJson(res, 200, { ok: true }); } const body = await readBody(req); const allowed = ['type', 'title', 'slug', 'excerpt', 'body', 'image_url', 'published', 'metadata']; const item = Object.fromEntries(allowed.filter(k => body[k] !== undefined).map(k => [k, body[k]])); if (!item.type || !item.title) return sendJson(res, 400, { ok: false, error: 'Type and title are required.' }); const result = await supabase(id ? `content_items?id=eq.${encodeURIComponent(id)}` : 'content_items', { method: id ? 'PATCH' : 'POST', headers: { Prefer: 'return=representation' }, body: JSON.stringify(item) }); return sendJson(res, id ? 200 : 201, { ok: true, item: Array.isArray(result) ? result[0] : result }); } catch (error) { return sendJson(res, 400, { ok: false, error: error.message }); } }
async function inquiryHandler(req, res) { try { const body = await readBody(req); const fields = ['name', 'email', 'phone', 'tour', 'dates', 'people', 'budget', 'message']; const cleaned = Object.fromEntries(fields.map(key => [key, String(body[key] ?? '').trim()])); if (!cleaned.name || !cleaned.email) return sendJson(res, 400, { ok: false, error: 'Name and email are required.' }); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(cleaned.email)) return sendJson(res, 400, { ok: false, error: 'Please enter a valid email address.' }); if (SUPABASE_KEY) await supabase('inquiries', { method: 'POST', body: JSON.stringify(cleaned) }); else console.log('New tour inquiry:', JSON.stringify(cleaned)); return sendJson(res, 200, { ok: true, message: 'Thanks — your request has been received. We will contact you shortly.' }); } catch (error) { return sendJson(res, 400, { ok: false, error: error.message || 'Invalid request.' }); } }
module.exports = { gallery, healthHandler, galleryHandler, contentHandler, inquiryHandler, adminLoginHandler, adminContentHandler };
